version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # ignore:
    #  - dependency-name: "react" # Specify dependencies to ignore
    #  - dependency-name: "vite"
