services:
  java-app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "9000:8090"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"