name: Build a JAR in spring boot using springboot
# Bron 9-1-2024: https://www.geeksforgeeks.org/spring-boot-continuous-integration-using-github-actions/
# De `on.push.branches` stond op `master`; dit moet `main` zijn, maar voor test doen we nu `gh-actions`.
on:
  push:
    branches:
      - gh-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1

        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Run Tests
        run: mvn test